CREATE TABLE department
(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(20) NOT NULL
);

CREATE TABLE sys_user
(
    id SERIAL PRIMARY KEY NOT NULL,
    login_name VARCHAR(128) NOT NULL,
    password VARCHAR(256) NOT NULL,
    name VARCHAR(128) NOT NULL,
    department_id INT,
    FOREIGN KEY ( department_id ) REFERENCES department ( id )
);

CREATE TABLE organization
(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(20) NOT NULL,
  pid INT NOT NULL,
  type VARCHAR(10)
);

ALTER TABLE sys_user
ALTER COLUMN login_name TYPE VARCHAR(128),
ALTER COLUMN password TYPE VARCHAR(256),
ALTER COLUMN name TYPE VARCHAR(128),
ALTER COLUMN gender TYPE VARCHAR(16);